# Generated by Django 6.0.4 on 2026-04-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills_totales', models.IntegerField()),
                ('muertes_totales', models.IntegerField()),
                ('asistencias_totales', models.IntegerField()),
                ('winrate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=16)),
                ('tag', models.CharField(max_length=5)),
                ('rango', models.CharField(max_length=16)),
                ('nivel', models.IntegerField()),
                ('agente_favorito', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapa', models.CharField(max_length=16)),
                ('kills', models.IntegerField()),
                ('muertes', models.IntegerField()),
                ('asistencias', models.IntegerField()),
                ('resultado', models.CharField(max_length=16)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
